# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python
#condition: succeededOrFailed()
trigger:
- master
- '*'

pool:
  vmImage: 'windows-latest'
strategy:
  matrix:
    Python38:
      python.version: '3.8'

steps:


- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
  displayName: Add conda to PATH


- script: conda init cmd.exe
  displayName: Initialise Conda Variables

- script: conda --version
  displayName: Conda Version

- script: conda config --add channels conda-forge
  displayName: Add conda forge

- script: conda env create --file ./environments/environment.yml
  displayName: Create Anaconda environment

- script: |
    activate ExampleDeployment
    pytest --version
    pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=html
  displayName: 'pytest'

- script:
    ls
  displayName: 'top dir files'

- script: |
    cd tests
    ls
  displayName: 'second top dir files'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: 'junit/*.xml'
    testRunTitle: 'Publish test results for Python $(python.version)'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'